Repository msameerfarooq/Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#1 Added fractional knapsack
  C++/fractional-knapsack.cpp
Labels: hacktoberfest-accepted

#2 Added BinaryHeapSort in Java
  BinaryHeapSort.java
Labels: hacktoberfest-accepted

#3 Create README.md
  README.md
Labels: hacktoberfest-accepted

#4 Created guidelines for contributors
  CONTRIBUTING.md
  README.md
Labels: documentation, hacktoberfest-accepted

#5 Added Steganography in python
  Python/Steganography.py
Labels: hacktoberfest-accepted

#6 Added quick sort in java
  Java/QuickSort.java
Labels: hacktoberfest-accepted

#7 Added Max Difference within array in C++
  21. Dynamic Programming/MaxDifferenceInArray.cpp
Labels: hacktoberfest-accepted

#8 Added sorting algorithms in C++
  07. Sorting/Bubblesort.cpp
  07. Sorting/bucketsort.cpp
Labels: hacktoberfest-accepted

#9 Motion Detector
  Python/motionDetector.py
Labels: hacktoberfest-accepted

#10 added bubblesort program in java
  Java/Bubblesort.java
Labels: hacktoberfest-accepted

#12 Added Job Sequencing Problem in C++
  19. Greedy/Job Sequencing Problem.cpp
Labels: hacktoberfest-accepted

#13 Added Bitonic Sort in Python
  Python/Bitonic_Sort.py
Labels: hacktoberfest-accepted

#14 Added N meetings in one room problem
  19. Greedy/N meetings in one room.cpp
Labels: hacktoberfest-accepted

#15 Added Python Script for Shell Sort
  Python/Shell_sort.py
Labels: hacktoberfest-accepted

#17 Create MinMaxElementsOfArray.java
  05. Arrays/MinMaxElementsOfArray.java
Labels: hacktoberfest-accepted

#18 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement, hacktoberfest-accepted

#24 Create Taylor_Series.cpp
  04. Recursion/Taylor_Series.cpp
Labels: hacktoberfest-accepted

#22 Added
  18. Graph/Codechef_CP_Q1.cpp
Labels: hacktoberfest-accepted

#20 QuickSort
  07. Sorting/Quicksort.cpp
Labels: hacktoberfest-accepted

#21 Create Arithmetic Operators.java
  Java/Arithmetic Operators.java
Labels: hacktoberfest-accepted

#25 Create Tarjan_Algorithm.cpp
  Tarjan_Algorithm.cpp
Labels: hacktoberfest-accepted

#28 Code for Suduko Solver is added
  09. Hashing/Suduko_Solver.cpp
Labels: hacktoberfest-accepted

#27 Create Floor_in_BST.cpp
  16. Binary Search Tree/Floor_in_BST.cpp
Labels: hacktoberfest-accepted

#26 Create insertionsort.cpp
  07. Sorting/insertionsort.cpp
Labels: hacktoberfest-accepted

#30 Created pascalstriangle.cpp
  21. Dynamic Programming/pascalstriangle.cpp
Labels: hacktoberfest-accepted

#31 Added Heap_Sort Program in Java Language
  Java/Heap_Sort.java
Labels: hacktoberfest-accepted

#35 Heap sort algorithm in python
  Python/Heap_Sort_Algorithm.py
Labels: hacktoberfest-accepted

#34 Create InfixToPrefix.cpp
  12. Stack/InfixToPrefix.cpp
Labels: hacktoberfest-accepted

#33 Create Longest_common_increasing_subsequence.cpp
  21. Dynamic Programming/Longest_common_increasing_subsequence.cpp
Labels: hacktoberfest-accepted

#32 Create 3sum.cpp
  05. Arrays/3sum.cpp
Labels: hacktoberfest-accepted

#38 Create left_most_deletion.cpp
  09. Hashing/left_most_deletion.cpp
Labels: hacktoberfest-accepted

#37 Update Check perfect square.cpp
  06. Searching/Check perfect square.cpp
Labels: hacktoberfest-accepted

#39 Rat Maze
  20. Backtracking/ratMaze.cpp
Labels: hacktoberfest-accepted

#36 added diagonal_sort.cpp
  08. Matrix/diagonal_sort.cpp
Labels: hacktoberfest-accepted

#41 adding code for pathsum ll
  15. Tree/path_Sum.cpp
Labels: hacktoberfest-accepted

#40 Add files via upload
  Python/githublogo.py
  Python/gitlogo.py
Labels: hacktoberfest-accepted

#42 Added Linked Stack in Java
  Java/LinkedStack.java
Labels: hacktoberfest-accepted

#43 Added Palindrome in Java
  Java/Palindrome.java
Labels: hacktoberfest-accepted

#44 Added Minesweeper
  Minesweeper/app.js
  Minesweeper/index.html
  Minesweeper/style.css
Labels: hacktoberfest-accepted

#45 Added anagram in C++
  03. Bit Magic/anagram.cpp
Labels: hacktoberfest-accepted

#48 Sum of max and min in window size k
  13. Queue/.vscode/settings.json
  13. Queue/SumOfMinMaxOfSizeK.cpp
Labels: hacktoberfest-accepted

#47 Added Longest Common Subsequence
  21. Dynamic Programming/longestCommonSubsequence.cpp
  21. Dynamic Programming/longestCommonSubsequence.exe
Labels: hacktoberfest-accepted

#49 Added Hangman game in python
  Python/HANGMAN_GAME.py
Labels: hacktoberfest-accepted

#51 Heap Sort added
  07. Sorting/HeapSort.cpp
Labels: hacktoberfest-accepted

#50 Finding Single Element where every element Twice
  03. Bit Magic/findSingleElementInArrayWhereEveryElementPresentTwice.cpp
  03. Bit Magic/findSingleElementInArrayWhereEveryElementPresentTwice.exe
Labels: hacktoberfest-accepted

#52 rotate by 90 degrees
  08. Matrix/RotateBy90Deg.cpp
Labels: hacktoberfest-accepted

#54 Add java code for MergeSort
  Java/MergeSort.java
Labels: hacktoberfest-accepted

#56 Added matrix sorting
  07. Sorting/column wise sorting of 2 d matrix.cpp
Labels: hacktoberfest-accepted

#60 Transpose added
  08. Matrix/Transpose of 2 d matrix.cpp
Labels: hacktoberfest-accepted

#59 Find First and Last Position of Element in Sorted Array
  06. Searching/Find First and Last Position of Element in Sorted Array.cpp
Labels: hacktoberfest-accepted

#61 Palindrome
  10. String/Palindrome.cpp
Labels: hacktoberfest-accepted

#58 factorial of a number
  04. Recursion/Factorial.cpp
Labels: hacktoberfest-accepted

#57 factorial of a number cpp
  02. Mathematics/factorial of a number.cpp
Labels: hacktoberfest-accepted

#62 row wise sorting of 2 d matrix
  07. Sorting/row wise sorting of 2 d array.cpp
Labels: hacktoberfest-accepted

#65 Photo to Sketch Converter
  Python/MS_DHONI.png
  Python/MS_DHONI_SKETCH.png
  Python/sketch.py
Labels: hacktoberfest-accepted

#64 Added a program to print all subsets using bit manipulation in C++
  03. Bit Magic/print-all-subsets.cpp
Labels: hacktoberfest-accepted

#63 quick-sort.cpp
  04. Recursion/quick-sort.cpp
Labels: hacktoberfest-accepted

#69 created fibonacci.cpp
  04. Recursion/fibonacci.cpp
Labels: hacktoberfest-accepted

#68 Added reverse_linked_list.cpp
  11. Linked List/reverse_linked_list.cpp
Labels: hacktoberfest-accepted

#67 codes added
  05. Arrays/kth_min_max_array.cpp
  05. Arrays/max_sum_subarray.cpp
  05. Arrays/min_jumps_end.cpp
  05. Arrays/minimize_max_difference.cpp
  05. Arrays/move_negative.cpp
  05. Arrays/reverse_array.cpp
  05. Arrays/rotate_array.cpp
  05. Arrays/sort_012_array.cpp
  05. Arrays/union_intersection.cpp
Labels: hacktoberfest-accepted

#66 Counting Sort
  07. Sorting/countingSort.cpp
Labels: hacktoberfest-accepted

#70 Added Search in rotated sorted array
  06. Searching/Search in Rotated Sorted Array.cpp
Labels: hacktoberfest-accepted

#71 Fidget Spinner
  Python/FidgetSpinner.py
Labels: hacktoberfest-accepted

#72 kadanes-algorithm(max subarray sum)
  05. Arrays/kadanes_algorithm.cpp
Labels: hacktoberfest-accepted

#73 Added a c++ program to find nth catalan number
  02. Mathematics/5. Nth_catalan_number.cpp
Labels: hacktoberfest-accepted

#74 Added Sudoku Solver
  Python/sudoku_solver.py
Labels: hacktoberfest-accepted

#75 added reverse string using stack
  12. Stack/reverse_string_using_stack.cpp
Labels: hacktoberfest-accepted

#79 Hello world added for java
  Java/HelloWorld.java
Labels: hacktoberfest-accepted

#81 Closed scanner in BubbleSort
  Java/Bubblesort.java
Labels: hacktoberfest-accepted

#82 Fixed InsertionSort
  Java/InsertionSort.java
Labels: hacktoberfest-accepted

#85 Tried to fix LinkedStack
  05. Arrays/MinMaxElementsOfArray.java
  Java/LinkedStack.java
Labels: hacktoberfest-accepted

#86 Added Graph Problem in Java
  Java/CountingTheNumberOfPathsToReachFrom1ToN.java
Labels: hacktoberfest-accepted

#87 Added Tic Tac Toe in Python
  Python/tic_tac_toe_game.py
Labels: hacktoberfest-accepted

#89 Added Occurrence of Characters within String in Java
  Java/OccurenceOfCharInString.java
  Python/dfs.py
Labels: hacktoberfest-accepted

#90 Added two sum problem in C++
  09. Hashing/TwoSum.cpp
Labels: hacktoberfest-accepted

#92 added a code random_quote.py
  Python/random_quote.py
Labels: enhancement, hacktoberfest-accepted

#84 Added bubble sort in python
  Python/bubble_sort
Labels: hacktoberfest-accepted

#78 Finding a Pair of Elements with sum K in an array.cpp
  05. Arrays/Finding a Pair of Elements with sum K in an array.cpp
Labels: hacktoberfest-accepted

#96 minimum value in an array
  05. Arrays/minvalue.cpp
Labels: hacktoberfest-accepted

#97 Create Pallindrome.java
  Pallindrome.java
Labels: hacktoberfest-accepted

#98 added linked list implementation
  11. Linked List/CircularLL.cpp
  11. Linked List/DoublyLL.cpp
  11. Linked List/SingleLL.cpp
Labels: hacktoberfest-accepted

#99 Create ComplimentOfBase10Integer.java
  ComplimentOfBase10Integer.java
Labels: hacktoberfest-accepted

#100 Add files via upload
  autofiltrie.cpp
Labels: hacktoberfest-accepted

#101 Create Maximum Area Histogram.cpp
  12. Stack/Maximum Area Histogram.cpp
Labels: hacktoberfest-accepted

#102 Added Codes in Trees
  15. Tree/DiameterOfBinaryTree.cpp
  15. Tree/Search_in_Binary_Search_Tree.cpp
Labels: hacktoberfest-accepted

#103 Stack using Linked List
  12. Stack/stack_using_LL.c
Labels: hacktoberfest-accepted

#104 Leetcode problem on merging sorted array
  05. Arrays/Merge Sorted Array.cpp
Labels: hacktoberfest-accepted

#105 Create Package.java
  Package.java
Labels: hacktoberfest-accepted

#106 Dynamic Programming
  21. Dynamic Programming/Scramble_String.cpp
  21. Dynamic Programming/wildcard_matching.cpp
Labels: hacktoberfest-accepted

#107 Create Palindromic Linked List.cpp
  11. Linked List/Palindromic Linked List.cpp
Labels: hacktoberfest-accepted

#108 Created odd_one_out.cpp
  05. Arrays/odd_one_out.cpp
Labels: hacktoberfest-accepted

#109 Delete_A_Node_In_a_Linked_List.cpp
  11. Linked List/Delete_node.cpp
Labels: hacktoberfest-accepted

#110 created longest common subsequence
  10. String/LongestCommonSubsequence.cpp
Labels: hacktoberfest-accepted

#111 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement

#113 Create sum_of_fibonacci(The_Sum_codeforces).cpp
  02. Mathematics/sum_of_fibonacci(The_Sum_codeforces).cpp
Labels: hacktoberfest-accepted

#115 Create Selection_sort.java
  Java/Selection_sort.java
Labels: hacktoberfest-accepted

#116 Create Odd_Divisor(codeforces).cpp
  02. Mathematics/Odd_Divisor(codeforces).cpp
Labels: hacktoberfest-accepted

#114 Create Travelling_Salesman_Problem
  Travelling_Salesman_Problem
Labels: hacktoberfest-accepted

#118 Create day display
  day display
Labels: hacktoberfest-accepted

#119 wrote a code for rock paper scissor game
  Python/RockPaperScissor.py
Labels: hacktoberfest-accepted

#120 LinearSearch.java
  Java/LinearSearch.java
Labels: hacktoberfest-accepted

#121 FibonacciSeries.java
  Java/FibonacciSeries.java
Labels: hacktoberfest-accepted

#122 Sorting array using stack
  12. Stack/Sorting array using Stacks
Labels: hacktoberfest-accepted

#123 Checking Graph
  18. Graph/Checking Graph
Labels: hacktoberfest-accepted

#130 Revert "Create trapping_rain_water.cpp"
  05. Arrays/trapping_rain_water.cpp
Labels: hacktoberfest-accepted

#126 Add files via upload
  Java/0237-delete-node-in-a-linked-list
  Java/Counting_sort.java
Labels: hacktoberfest-accepted

#127 created Sports_Mafia.cpp file
  06. Searching/Sport_Mafia.cpp
Labels: hacktoberfest-accepted

#129 Patternprogram.cpp
  Patternprogram.cpp
Labels: hacktoberfest-accepted

#133 Create Cycle Sort.cpp
  07. Sorting/Cycle Sort.cpp
Labels: hacktoberfest-accepted

#132 Create hanoi_towers.cpp
  04. Recursion/hanoi_towers.cpp
Labels: hacktoberfest-accepted

#134 Create cycle-sort.cpp
  07. Sorting/cycle-sort.cpp
Labels: hacktoberfest-accepted

#141 Update 4. Move all zeroes to end of array.cpp
  05. Arrays/4. Move all zeroes to end of array.cpp
Labels: hacktoberfest-accepted

#135 Added 2 programs (Language - Java)
  11. Linked List/remove_duplicates.java
  11. Linked List/swap_2_nodes.java
Labels: hacktoberfest-accepted

#154 Added 1 python program and 2 js programs
  Javascript/age_calculator.js
  Javascript/bmi_calculator.js
  Python/merge_list.py
Labels: hacktoberfest-accepted

#155 array codes added
  05. Arrays/duplicate_in_array.cpp
  05. Arrays/merge_interval.cpp
  05. Arrays/next_permutation.cpp
Labels: hacktoberfest-accepted

#149 Polynomial
  11. Linked List/Polynomial.c
Labels: hacktoberfest-accepted

#148 Added 3 programs under BST (in Java)
  16. Binary Search Tree/largest_BST_subtree.java
  16. Binary Search Tree/level_wise_LL.java
  16. Binary Search Tree/pair_sum_in_a_BST.java
Labels: hacktoberfest-accepted

#136 created an array program
  05. Arrays/array_program.cpp
Labels: hacktoberfest-accepted

#137 Update minvalue.cpp
  05. Arrays/minvalue.cpp
Labels: hacktoberfest-accepted

#145 Added a game , guessmovie
  Python/guessmovie.py
Labels: hacktoberfest-accepted

#160 Gale Shapely Matching Algorithm
  19. Greedy/gale_shapely.py
Labels: hacktoberfest-accepted

#153 Added First Unique Character in a String solution
  09. Hashing/first_unique_chracter_in_a_string.cpp
Labels: hacktoberfest-accepted

#163 Create Flood fill algorithm.cpp
  18. Graph/Flood fill algorithm.cpp
Labels: hacktoberfest-accepted

#156 Create ConstructBinaryTree.cpp
  16. Binary Search Tree/ConstructBinaryTree.cpp
Labels: hacktoberfest-accepted

#161 C++ code for LCM and HCF.
  02. Mathematics/hcf_and_lcm.cpp
Labels: hacktoberfest-accepted

#166 palindrome.js
  Javascript/palindrome.js
Labels: hacktoberfest-accepted

#151 Create Stock Span Problem.cpp
  12. Stack/Stock Span Problem.cpp
Labels: hacktoberfest-accepted

#177 Create SublistSearch.cpp
  06. Searching/SublistSearch.cpp
Labels: hacktoberfest-accepted

#157 Create house-robber
  Java/house-robber
Labels: hacktoberfest-accepted

#173 Create InterpolationSearch.cpp
  06. Searching/InterpolationSearch.cpp
Labels: hacktoberfest-accepted

#178 Convert linked list into binary tree
  11. Linked List/linked_list_to_binary_tree.cpp
Labels: hacktoberfest-accepted

#138 Update 1. Remove duplicate elements from sorted Array.cpp
  05. Arrays/1. Remove duplicate elements from sorted Array.cpp
Labels: hacktoberfest-accepted

#150 Added two problems- Edit distance and printing Longest Increasing Subsequence in Dynamic Programming Folder
  21. Dynamic Programming/EditDistance.cpp
  21. Dynamic Programming/PrintingLongestIncreasingSubsequence.cpp
Labels: hacktoberfest-accepted

#180 Create GraphImplementation.java
  18. Graph/GraphImplementation.java
Labels: hacktoberfest-accepted

#181 Added binary search in java
  16. Binary Search Tree/BinaryTree.java
Labels: hacktoberfest-accepted

#186 Create odd_even_check.py
  03. Bit Magic/odd_even_check.py
Labels: hacktoberfest-accepted

#185 MouseListener , MouseMotionListener in java
  Java/MouseListener , MouseMotionListener in java/MouseDemo.java
  Java/MouseListener , MouseMotionListener in java/Screenshot-1.jpg
  Java/MouseListener , MouseMotionListener in java/Screenshot-2.jpg
  Java/MouseListener , MouseMotionListener in java/Screenshot-3.jpg
Labels: hacktoberfest-accepted

#171 Create buy_and_sell_stock_1.cpp
  21. Dynamic Programming/buy_and_sell_stock_1.cpp
Labels: hacktoberfest-accepted

#158 Create binarysearchtree.py
  Python/binarysearchtree.py
Labels: hacktoberfest-accepted

#183 Create bubble_sort.cpp
  05. Arrays/bubble_sort.cpp
Labels: hacktoberfest-accepted

#143 nQueen
  nQUEEN.cpp
Labels: hacktoberfest-accepted

#147 Minimum Path Sum
  05. Arrays/Minimum Path Sum.cpp
Labels: hacktoberfest-accepted

#213 Hollow Diamond
  General/Hollow Diamond.cpp
Labels: question, hacktoberfest-accepted

#211 Create RedBlackTree.cpp
  15. Tree/RedBlackTree.cpp
Labels: hacktoberfest-accepted

#204 Even or odd number
  Source.cpp
Labels: hacktoberfest-accepted

#162 Added Linear search cpp code
  06. Searching/linear_search.cpp
Labels: hacktoberfest-accepted

#165 Create elimination_game.cpp
  04. Recursion/elimination_game.cpp
Labels: hacktoberfest-accepted

#192 Create 4Sum.cpp
  05. Arrays/4Sum.cpp
Labels: hacktoberfest-accepted

#193 Top_2_Maximum_number_in_Array
  05. Arrays/Top_2_Maximum_number_in_Array.cpp
Labels: hacktoberfest-accepted

#200 JAVA Program to find VOLUME
  Java/Volume.java
Labels: hacktoberfest-accepted
